#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "167.205.33.209";
$SERVER_PORT = 8279;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
